/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AcknowledgeEvent } from "./components/my-card/my-card";
export namespace Components {
    interface MyButton {
        "btnname": string;
        "buttonname": string;
        "label": string;
    }
    interface MyCard {
        "kind": 'info' | 'success' | 'error';
        "text": string;
    }
}
export interface MyCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyCardElement;
}
declare global {
    interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {
    }
    var HTMLMyButtonElement: {
        prototype: HTMLMyButtonElement;
        new (): HTMLMyButtonElement;
    };
    interface HTMLMyCardElement extends Components.MyCard, HTMLStencilElement {
    }
    var HTMLMyCardElement: {
        prototype: HTMLMyCardElement;
        new (): HTMLMyCardElement;
    };
    interface HTMLElementTagNameMap {
        "my-button": HTMLMyButtonElement;
        "my-card": HTMLMyCardElement;
    }
}
declare namespace LocalJSX {
    interface MyButton {
        "btnname"?: string;
        "buttonname"?: string;
        "label"?: string;
    }
    interface MyCard {
        "kind"?: 'info' | 'success' | 'error';
        "onAcknowledge"?: (event: MyCardCustomEvent<AcknowledgeEvent>) => void;
        "text"?: string;
    }
    interface IntrinsicElements {
        "my-button": MyButton;
        "my-card": MyCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-button": LocalJSX.MyButton & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
            "my-card": LocalJSX.MyCard & JSXBase.HTMLAttributes<HTMLMyCardElement>;
        }
    }
}
